In [ ]:
#Introduction to Pandas:
#Pandas is an open source library which is used for handling data manipulations.

In [1]:
import pandas as pd

In [ ]:
# Data Structure of Pandas:
# 1.Series --> It is one dimensional array and it returns only values not column name.
# 2. Data Frame --> It is multi-dimensional array and it returns only value with column name.

In [ ]:
# Series

In [5]:
a = pd.Series([1,34,78,90])
a

0     1
1    34
2    78
3    90
dtype: int64

In [6]:
type(a)

pandas.core.series.Series

In [ ]:
# Data Frame

In [9]:
a = {
    "Emp_ID": ['A101','A102','A103','A104','A105','A106'],
    "Emp_Name":['Sam','Rahul','Aniket','Gorav','Mohit','Karan'],
    "Department":['IT','Operations','IT','IT','Operations','IT'],
    "Salary" : [20000,25000,35000,21000,40000,45000],
    "Working_hours": [8,8,9,9,9,8]
}

In [10]:
type(a)

dict

In [11]:
df = pd.DataFrame(a)
df

  Emp_ID Emp_Name  Department  Salary  Working_hours
0   A101      Sam          IT   20000              8
1   A102    Rahul  Operations   25000              8
2   A103   Aniket          IT   35000              9
3   A104    Gorav          IT   21000              9
4   A105    Mohit  Operations   40000              9
5   A106    Karan          IT   45000              8

In [ ]:
# export this df into csv

In [12]:
df.to_csv("emp_data.csv")

In [13]:
df.to_csv("emp_data_new.csv", index=False)